import {
    Wc,
    Subway,
    Wifi,
    Restaurant,
    LocalParking,
    AcUnit,
    Pool,
    FitnessCenter,
    Pets,
    SmokingRooms,
    LocalBar,
    HelpOutline,
    MarkunreadMailbox,
    Phone, 
    Luggage,
    Atm,
    AirportShuttle,
    Architecture,
    Web,
    VideoLabel,
    Translate,
    Train,
    TheaterComedy,
    TempleBuddhist,
    Surfing,
    Store,
    Skateboarding,
    SignalCellularNodata,
    Attractions,
    Castle,
    Church,
    Coffee,
    Elevator,
    Forest,
    IceSkating
} from '@mui/icons-material';

// Icon mapping based on facility code
const facilityIcons = {
    Wc: Wc,
    Subway: Subway,
    Wifi: Wifi,
    Restaurant: Restaurant,
    Parking: LocalParking,
    AC: AcUnit,
    Pool: Pool,
    Gym: FitnessCenter,
    Pets: Pets,
    Smoking: SmokingRooms,
    Bar: LocalBar,
    LocalPostOffice: MarkunreadMailbox,
    Phone: Phone,
    Luggage: Luggage,
    Atm: Atm,
    AirportShuttle: AirportShuttle,
    Architecture: Architecture,
    Web: Web,
    VideoLabel: VideoLabel,
    Translate: Translate,
    Train: Train,
    TheaterComedy: TheaterComedy,
    TempleBuddhist: TempleBuddhist,
    Surfing: Surfing,
    Store: Store,
    Skateboarding: Skateboarding,
    SignalCellularNodata: SignalCellularNodata,
    Attractions: Attractions,
    Castle: Castle,
    Church: Church,
    Coffee: Coffee,
    Elevator: Elevator,
    Forest: Forest,
    IceSkating: IceSkating
};

function FacilityIcon({ code, ...props }) {
    const IconComponent = facilityIcons[code] || HelpOutline;
    return <IconComponent {...props} />;
}

export default FacilityIcon;